name: aktien_analyse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11 
  - pandas
  - numpy
  
  - yfinance
 
  - sqlalchemy
  - openpyxl 
  - pip
  - pip:
     - matplotlib
     - pyqt6 
